import { Inter } from 'next/font/google'
import './globals.css'

import { connection } from "@/app/lib/database";
import mongoose from "mongoose";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function  RootLayout({ children }) {
 
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
